---
################################################################
###                    *** WARNING ***
################################################################
###
### ALMOST EVERYTHING REQUESTED IN THIS FILE ARE CONFIDENTIAL CREDENTIALS
### IF YOU POST THIS FILE ONLINE (such as on GitHub) YOUR BOT COULD BE COMPROMISED
###
###
### Use a proper text editor when editing this file, for example Sublime.
### Do not use tab characters in this file, use plain spaces.
###
### Keep at least one space after a colon, like so:
###
###   key: value
###
###
### Never edit or add a value to lines that have no default value, like:
###
###   credentials:
###
### Just leave them be. A default value may be an empty string like so: ""
###
###
### You can wrap most values into quotation marks, except numbers and booleans:
###
###   someUrl: "http://example.com"
###   someToken: "123.qwe.456[DFG="
###   somePortNumber: 22
###   useSomeFeature: true
###
###
### You can have a list of things like this:
###
###   listOfStrings: ["string1", "string2", "string3"]
###
### or like this:
###
###   listOfStrings:
###     - "string1"
###     - "string2"
###     - "string3"
###
###
### More information on correctly formatting yaml files: http://www.yaml.org/start.html

security:
  admins:
  # Set a name and a pass. These have to be the same as set up in the fredboat.yaml
  # Do not leave any of them blank or empty.
  - name: ""
    pass: ""

whitelist:
  userIds:                   # a list of discord user ids that shall never be ratelimited or blacklisted
  - 81011298891993088
  - 166604053629894657

spring:
  main:
    banner-mode: log
  output:
    ansi:
      enabled: detect                # for developers: setting this to "always" will force colored logs in your console

server:
  port: 4269                         # port of the backend

sentry:
  dsn: ""

# If you are using docker to host the whole FredBoat, you can ignore all database settings below this line.
database:
  main:
    # FredBoat was written to work with PostgreSQL.
    # If you are running with docker-compose then you don't need to change the jdbcUrl here.
    # In PostgreSQL, role means user and vice versa. Keep that in mind when reading the following help and the provided links.
    # If you are running your own PostgreSQL database, you will need to provide a role and a database belonging to that role.
    # The role needs at least the permission to log in.
    # All postgres databases used by FredBoat are required to have the Hstore extension enabled.
    # Learn more about roles here: https://www.postgresql.org/docs/10/static/database-roles.html
    # Learn more about creating databases here: https://www.postgresql.org/docs/10/static/manage-ag-createdb.html
    # Learn more about the postgres jdbc url here: https://jdbc.postgresql.org/documentation/head/connect.html
    # Learn more about creating extensions here: https://www.postgresql.org/docs/current/static/sql-createextension.html
    # Example jdbc: "jdbc:postgresql://localhost:5432/fredboat?user=fredboat&password=youshallnotpass"
    jdbcUrl: ""

  cache:
    # Database for caching things, see config of main database above for details about the individual values.
    # If you are running with docker-compose then you don't need to change the cache jdbcUrl here.
    # The main and cache databases can be two databases inside a single postgres instance.
    # They CANNOT be the same database due to the way flyway migrations work.
    # The main benefit is that you don't have to backup/migrate the cache database, it can just be dropped/recreated
    # If you do not provide a jdbc url for the cache database, FredBoat will still work (most likely), but may have a degraded
    # performance, especially in high usage environments and when using Spotify playlists.
    jdbcUrl: ""

# tune these according to your needs, or just leave them as is.
logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

  level:
    root: INFO
    fredboat: DEBUG
    com.fredboat: DEBUG

docs:
  open: false               # Open the documentation endpoints for the public, and disable certain security features.
  # DO NOT OPEN these on a production system.
  host: ""                  # Reference: https://swagger.io/docs/specification/2-0/api-host-and-base-path/
  basePath: ""              # Tell swagger where to find this Quarterdeck for Try out queries
